apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docdb-secret
  namespace: amazona
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: docdb-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: prod/amazona/docdb
        property: username
    - secretKey: password
      remoteRef:
        key: prod/amazona/docdb
        property: password
